# Generated by Django 5.1 on 2024-08-28 08:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0002_news_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
