# Generated by Django 5.1 on 2024-08-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0003_news_publish_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='top_image',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
