# Generated by Django 5.1 on 2024-09-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0006_alter_news_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='top_image',
            field=models.ImageField(blank=True, null=True, upload_to='news/'),
        ),
    ]
