# Generated by Django 5.1 on 2024-09-14 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_news', '0008_news_aithor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='aithor',
            new_name='author',
        ),
    ]
